<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ZipCode</name>
   <tag></tag>
   <elementGuidId>cca3fe8b-1401-4a59-9d4e-82ccc629eafd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='dwfrm_membersettings_zipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='dwfrm_membersettings_zipcode']</value>
   </webElementProperties>
</WebElementEntity>
