<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MultipleAddNumber</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-03-24T13:58:18</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5f17a2b7-a181-4d30-b12c-38b61596a2b6</testSuiteGuid>
   <testCaseLink>
      <guid>6e4bf721-d6fa-41e2-ab2d-e17cf70ddc04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Assignment1/AddOperation</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>ba71cdcf-b5b4-4ed1-9098-be2918ce8089</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Assignment1/AddNumber</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ba71cdcf-b5b4-4ed1-9098-be2918ce8089</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Number1</value>
         <variableId>6424134e-6547-4382-9fee-63f7b105e24a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba71cdcf-b5b4-4ed1-9098-be2918ce8089</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Number2</value>
         <variableId>792899fe-4d4a-47be-a7f2-ab5c10ccc710</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
