<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ListOfOfficeProductNames</name>
   <tag></tag>
   <elementGuidId>ca62065a-5d87-488f-8ae3-e2cc97380d1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='visualnav1_rr']//li//h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='visualnav1_rr']//li//h3</value>
   </webElementProperties>
</WebElementEntity>
