<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zipCode</name>
   <tag></tag>
   <elementGuidId>0a877a09-1f7b-4d67-b6ce-2bd787654c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='dwfrm_storelocator_postalCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='dwfrm_storelocator_postalCode']</value>
   </webElementProperties>
</WebElementEntity>
